name: Metrics

on:
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics embed
        uses: lowlighter/metrics@v3.29
        with:
          token: ${{ secrets.METRICS_TOKEN }}
